# R Bootcamp: Session 1

# R Variables
- variables are containers for storing variables


## Creating and using Variables

In [2]:
a<-10
b<-5

In [3]:
c<-a+b
c

[1] 15

#### difference between <- and = (= doesnt work in a loop)

In [4]:
a<-20

In [5]:
a=10

In [6]:
a

[1] 10

In [7]:
typeof(a)

[1] "double"

In [8]:
c=15.0
typeof(c)

[1] "double"

# performing operation
. doesnt quantify anything 
we can have . in variable names

In [9]:
var.a=2.5
var.b<-4

result<- var.a/var.b

In [10]:
var.a

[1] 2.5

In [11]:
result.a<-sqrt(var.a)
result.a

[1] 1.581139

In [12]:
typeof(result.a)

[1] "double"

In [13]:
print(result.a)

[1] 1.581139


# Logical Variables and operators

In [14]:
4<5

[1] TRUE

In [15]:
4==5

[1] FALSE

In [16]:
result<-4<5
result

[1] TRUE

In [17]:
typeof(result)

[1] "logical"

# logical operators

In [18]:
resulta<-!TRUE
resulta

[1] FALSE

In [19]:
resulta|result

[1] TRUE

In [20]:
resulta & result

[1] FALSE

# Process Control

## while loop

In [21]:
n=0
while(n<10){
    n=n+1
    print(n)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


## break

In [22]:
i<-1
while(i<10){
    print(i)
    i<-i+1
    if (i==4){
        break
    }
}

[1] 1
[1] 2
[1] 3


## For

In [23]:
## For Loop
fruits <- list('apples','banana','mango')

for (x in fruits){
    print(x)
}

[1] "apples"
[1] "banana"
[1] "mango"


In [24]:
# RStudio works differently
colors <- list('red', 'blue', 'green')
for (x in colors){
    print(x)
}
print(colors)

[1] "red"
[1] "blue"
[1] "green"
[[1]]
[1] "red"

[[2]]
[1] "blue"

[[3]]
[1] "green"



In [25]:
# paste command
for (x in fruits){
    for (y in colors){
        print(paste(x,y))
    }
}

[1] "apples red"
[1] "apples blue"
[1] "apples green"
[1] "banana red"
[1] "banana blue"
[1] "banana green"
[1] "mango red"
[1] "mango blue"
[1] "mango green"


# R bootcamp: Session 2

## Vectors
A vector is a simply a list of items that are of the same type. To combine the list of items to a vecot,  use the c() function and separate the items by a comma

In [26]:
v1<- c(3,4,56,77,4,5)
v1

[1]  3  4 56 77  4  5

In [27]:
typeof(v1)

[1] "double"

In [28]:
v2<- c(23,55,66,88,12)
# v2<-as.vector(v2)
typeof(v2)
is.integer(v2)

[1] "double"

[1] FALSE

In [29]:
for(x in v2){
    print(x)
}

[1] 23
[1] 55
[1] 66
[1] 88
[1] 12


In [30]:
?c

c                     package:base                     R Documentation

_C_o_m_b_i_n_e _V_a_l_u_e_s _i_n_t_o _a _V_e_c_t_o_r _o_r _L_i_s_t

_D_e_s_c_r_i_p_t_i_o_n:

     This is a generic function which combines its arguments.

     The default method combines its arguments to form a vector.  All
     arguments are coerced to a common type which is the type of the
     returned value, and all attributes except names are removed.

_U_s_a_g_e:

     ## S3 Generic function
     c(...)
     
     ## Default S3 method:
     c(..., recursive = FALSE, use.names = TRUE)
     
_A_r_g_u_m_e_n_t_s:

     ...: objects to be concatenated.

recursive: logical.  If 'recursive = TRUE', the function recursively
          descends through lists (and pairlists) combining all their
          elements into a vector.

use.names: logical indicating if 'names' should be preserved.

_D_e_t_a_i_l_s:

     The output type is determined from the highest type of the
     components in the hierarchy NULL < raw < logical < integer <
     double < complex < character < list < expression.  Pairlists are
     treated as lists, whereas non-vector components (such names and
     calls) are treated as one-element lists which cannot be unlisted
     even if 'recursive = TRUE'.

     Note that 'factor's are treated only via their internal 'integer'
     codes; one proposal has been to use
     
        c.factor <- function(..., recursive=TRUE) unlist(list(...), recursive=recursive)

     if factor concatenation by 'c()' should give a 'factor'.

     'c' is sometimes used for its side effect of removing attributes
     except names, for example to turn an array into a vector.
     'as.vector' is a more intuitive way to do this, but also drops
     names.  Note that methods other than the default are not required
     to do this (and they will almost certainly preserve a class
     attribute).

     This is a primitive function.

_V_a_l_u_e:

     'NULL' or an expression or a vector of an appropriate mode.  (With
     no arguments the value is 'NULL'.)

_S_4 _m_e_t_h_o_d_s:

     This function is S4 generic, but with argument list '(x, ...)'.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'unlist' and 'as.vector' to produce attribute-free vectors.

_E_x_a_m_p_l_e_s:

     c(1,7:9)
     c(1:5, 10.5, "next")
     
     ## uses with a single argument to drop attributes
     x <- 1:4
     names(x) <- letters[1:4]
     x
     c(x)          # has names
     as.vector(x)  # no names
     dim(x) <- c(2,2)
     x
     c(x)
     as.vector(x)
     
     ## append to a list:
     ll <- list(A = 1, c = "C")
     ## do *not* use
     c(ll, d = 1:3) # which is == c(ll, as.list(c(d = 1:3)))
     ## but rather
     c(ll, d = list(1:3))  # c() combining two lists
     
     c(list(A = c(B = 1)), recursive = TRUE)
     
     c(options(), recursive = TRUE)
     c(list(A = c(B = 1, C = 2), B = c(E = 7)), recursive = TRUE)

In [31]:
?data.

No documentation for 'data.' in specified packages and libraries:
you could try '??data.'

In [32]:
v1

[1]  3  4 56 77  4  5

In [33]:
is.numeric(v1)

[1] TRUE

In [34]:
is.null(v1)

[1] FALSE

In [35]:
v1[5]

[1] 4

In [36]:
sort(v1)

[1]  3  4  4  5 56 77

## access specific intems within vector

In [37]:
v1[-1]

[1]  4 56 77  4  5

In [38]:
# range of index
v1[1:4]

[1]  3  4 56 77

In [39]:
# specific index 
v1[c(3,5)]

[1] 56  4

In [40]:
v1

[1]  3  4 56 77  4  5

# Matrix 
A matrix is a 2d data set with columns and rows

In [41]:
thismatrix<- matrix(c(1,2,3,4,5,7), ncol = 3, nrow = 2)
print(thismatrix)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    7


In [42]:
thismatrix

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    7

# Arrays
array can have more than 2 dimensions

In [43]:
thisarray <-c(1:24)
thisarray

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

In [44]:
multiArray<-array(thisarray, dim=c(2,3,2))
print(multiArray)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12



In [45]:
numbers=c(1L,2L,3L,4L)
is.integer(numbers)

[1] TRUE

In [46]:
a=5.0L
is.integer(a)

[1] TRUE

# R Bootcamp Session 3
data.table
this data.table is an alternative to R's default data.frame to handle tabular data
the reason its so popular is because of the speed od execution on large data and the tense syntax

In [50]:
library(data.table)

In [51]:
?fread

fread                package:data.table                R Documentation

_F_a_s_t _a_n_d _f_r_i_e_n_d_l_y _f_i_l_e _f_i_n_a_g_l_e_r

_D_e_s_c_r_i_p_t_i_o_n:

     Similar to 'read.table' but faster and more convenient. All
     controls such as 'sep', 'colClasses' and 'nrows' are automatically
     detected. 'bit64::integer64' types are also detected and read
     directly without needing to read as character before converting.

     Dates are read as character currently. They can be converted
     afterwards using the excellent 'fasttime' package or standard base
     functions.

     `fread` is for _regular_ delimited files; i.e., where every row
     has the same number of columns. In future, secondary separator
     ('sep2') may be specified _within_ each column. Such columns will
     be read as type 'list' where each cell is itself a vector.

_U_s_a_g_e:

     fread(input, file, text, cmd, sep="auto", sep2="auto", dec=".", quote="\"",
     nrows=Inf, header="auto",
     na.strings=getOption("datatable.na.strings","NA"),  # due to change to ""; see NEWS
     stringsAsFactors=FALSE, verbose=getOption("datatable.verbose", FALSE),
     skip="__auto__", select=NULL, drop=NULL, colClasses=NULL,
     integer64=getOption("datatable.integer64", "integer64"),
     col.names,
     check.names=FALSE, encoding="unknown",
     strip.white=TRUE, fill=FALSE, blank.lines.skip=FALSE,
     key=NULL, index=NULL,
     showProgress=getOption("datatable.showProgress", interactive()),
     data.table=getOption("datatable.fread.datatable", TRUE),
     nThread=getDTthreads(verbose),
     logical01=getOption("datatable.logical01", FALSE),  # due to change to TRUE; see NEWS
     keepLeadingZeros = getOption("datatable.keepLeadingZeros", FALSE),
     autostart=NA
     )
     
_A_r_g_u_m_e_n_t_s:

   input: A single character string. The value is inspected and
          deferred to either 'file=' (if no \n present), 'text=' (if at
          least one \n is present) or 'cmd=' (if no \n is present, at
          least one space is present, and it isn't a file name).
          Exactly one of 'input=', 'file=', 'text=', or 'cmd=' should
          be used in the same call.

    file: File name in working directory, path to file (passed through
          'path.expand' for convenience), or a URL starting http://,
          file://, etc. Compressed files ending '.gz' and '.bz2' are
          supported if the 'R.utils' package is installed.

    text: The input data itself as a character vector of one or more
          lines, for example as returned by 'readLines()'.

     cmd: A shell command that pre-processes the file; e.g.
          'fread(cmd=paste("grep",word,"filename")'.

     sep: The separator between columns. Defaults to the character in
          the set '[,\t |;:]' that separates the sample of rows into
          the most number of lines with the same number of fields. Use
          'NULL' or '""' to specify no separator; i.e. each line a
          single character column like 'base::readLines' does.

    sep2: The separator _within_ columns. A 'list' column will be
          returned where each cell is a vector of values. This is much
          faster using less working memory than 'strsplit' afterwards
          or similar techniques. For each column 'sep2' can be
          different and is the first character in the same set above
          [',\t |;'], other than 'sep', that exists inside each field
          outside quoted regions in the sample. NB: 'sep2' is not yet
          implemented.

   nrows: The maximum number of rows to read. Unlike 'read.table', you
          do not need to set this to an estimate of the number of rows
          in the file for better speed because that is already
          automatically determined by 'fread' almost instantly using
          the large sample of lines. `nrows=0` returns the column names
          and typed empty columns determined by the large sample

In [52]:
mt<-fread('https://raw.githubusercontent.com/selva86/datasets/master/mtcars.csv')

In [55]:
head(mt)

mpg      cyl disp hp  drat wt    qsec  vs am gear carb fast cars             
1 4.582576 6   160  110 3.90 2.620 16.46 0  1  4    4    1    Mazda RX4        
2 4.582576 6   160  110 3.90 2.875 17.02 0  1  4    4    1    Mazda RX4 Wag    
3 4.774935 4   108   93 3.85 2.320 18.61 1  1  4    1    1    Datsun 710       
4 4.626013 6   258  110 3.08 3.215 19.44 1  0  3    1    1    Hornet 4 Drive   
5 4.324350 8   360  175 3.15 3.440 17.02 0  0  3    2    1    Hornet Sportabout
6 4.254409 6   225  105 2.76 3.460 20.22 1  0  3    1    1    Valiant          
  carname          
1 Mazda RX4        
2 Mazda RX4 Wag    
3 Datsun 710       
4 Hornet 4 Drive   
5 Hornet Sportabout
6 Valiant

In [56]:
class(mt)

[1] "data.table" "data.frame"

In [59]:
nrow(mt)
ncol(mt)
str(mt)


[1] 32

[1] 14

Classes 'data.table' and 'data.frame':	32 obs. of  14 variables:
 $ mpg    : num  4.58 4.58 4.77 4.63 4.32 ...
 $ cyl    : int  6 6 4 6 8 6 8 4 4 6 ...
 $ disp   : num  160 160 108 258 360 ...
 $ hp     : int  110 110 93 110 175 105 245 62 95 123 ...
 $ drat   : num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt     : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec   : num  16.5 17 18.6 19.4 17 ...
 $ vs     : int  0 0 1 1 0 1 0 1 1 1 ...
 $ am     : int  1 1 1 0 0 0 0 0 0 0 ...
 $ gear   : int  4 4 4 3 3 3 3 4 4 4 ...
 $ carb   : int  4 4 1 1 2 1 4 2 2 4 ...
 $ fast   : int  1 1 1 1 1 1 0 1 1 1 ...
 $ cars   : chr  "Mazda RX4" "Mazda RX4 Wag" "Datsun 710" "Hornet 4 Drive" ...
 $ carname: chr  "Mazda RX4" "Mazda RX4 Wag" "Datsun 710" "Hornet 4 Drive" ...
 - attr(*, ".internal.selfref")=<externalptr> 


In [60]:
summary(mt)

      mpg             cyl             disp             hp       
 Min.   :3.225   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:3.927   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :4.382   Median :6.000   Median :196.3   Median :123.0  
 Mean   :4.435   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:4.775   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :5.822   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb            fast       
 Min.   :0.0000 

## $ operator will get the specific column form the dataframe

In [64]:
head(mt$vs)

[1] 0 0 1 1 0 1